### ISSUE TITLE
Cover art should be loaded based on the "coverArt" attribute

### ISSUE THREAD

**Issue by carlreinke** [airsonic/airsonic-ui#68] opened 2018-07-26 04:27 UTC
The `coverArt` attribute, not the `id` attribute, should be used in the `id` parameter of the query to `getCoverArt`.  If the (optional) `coverArt` attribute is omitted then some generic cover art should be displayed (e.g. a gray square or perhaps something more interesting).

**Comment by bfkelsey** [comment] 2019-02-09 18:46
This is a duplicate of #8

**Closed by bfkelsey** 2019-02-09 18:46 UTC
